# Generated by Django 5.2.4 on 2025-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_voyage',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='2025-12-31', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='nom',
            field=models.CharField(default='2025-12-31', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='nombre_personnes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prenom',
            field=models.CharField(default='2025-12-31', max_length=100),
            preserve_default=False,
        ),
    ]
