# Generated by Django 5.1.3 on 2025-08-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='reservations.reservation'),
        ),
    ]
